using Logging
import Dates

# check if docker runs
if success(run(`docker ps`; wait = false))
    @info "Docker is fine, starting generation."
else
    @error("`docker ps` failed, please check if docker runs. Exiting...")
    exit()
end

using Pkg
using HTTP, OpenAPI, JSON

function postprocess_docs(docsfolder)
    #=
    # this is implemented
        3. Replace `../README` with `./README` in all files in `docs/src`.
        6. Replace `[**`Vector{String}`**](String.md)` with `**`Vector{String}`**`.
        7. Replace `[**`Vector{Float32}`**]](Float32.md)` with `**`Vector{Float32}`**`.
        8. Replace `/images/device-attribution-image.png` with `images/device-attribution-image.png`.
        9. Replace `docs/` links with `./`.
    =#
    for (path, dirs, files) in walkdir(docsfolder)
        for file in files
            splitext(file)[2] != ".md" && continue
            f = joinpath(path, file)
            oldf = read(f, String)
            newf = replace(oldf, "../README" => "./README")
            newf = replace(newf, "[**`Vector{String}`**](String.md)" => "**`Vector{String}`**")
            newf = replace(newf, "[**`Vector{Float32}`**](Float32.md)" => "**`Vector{Float32}`**")
            newf = replace(newf, "/images/device-attribution-image.png" => "images/device-attribution-image.png")
            newf = replace(newf, "(docs/" => "(./")
            if file == "index.md"
                date_text = "Package code was generated at: `UTC $(Dates.now(Dates.UTC))`"
                newf = replace(newf, "<INSERT_DATE>" => date_text)
            end
            write(f, newf)
        end
    end

    return docsfolder
end

function postprocess_src(srcfolder)
    #=
    # this is implemented
        8. Replace `/images/device-attribution-image.png` with `images/device-attribution-image.png`.
    =#
    for (path, dirs, files) in walkdir(srcfolder)
        for file in files
            splitext(file)[2] != ".jl" && continue
            f = joinpath(path, file)
            oldf = read(f, String)
            newf = replace(oldf, "/images/device-attribution-image.png" => "images/device-attribution-image.png")
            write(f, newf)
        end
    end

    return srcfolder
end

function generatepackage()
    devdir = dirname(@__DIR__)
    docdir = joinpath(devdir, "docs")
    gendir = joinpath(devdir, "generator")
    cd(devdir)
    @info "Working in $devdir"

    readme_file = read(joinpath(devdir, "README.md"), String)

    try
        r = HTTP.get("https://developers.strava.com/swagger/swagger.json")
        d = JSON.parse(String(r.body), dicttype = Dict{String, Any})
        @info "Downloaded and parsed API definition."

        OpenAPI.openapi_generator()
        @info "Started OpenAPI container, waiting little bit..."
        sleep(5) # sleeping, cause it helped a few times
        OpenAPI.generate(d; package_name = "StravaAPI", output_dir = devdir)
        OpenAPI.stop_openapi_generator()
    catch e
        @error "Something failed horribly. Exiting..."
        println(e)
        exit()
    end
    @info "Package code generated with OpenAPI, continuing with postprocessing."

    cd(devdir)
    mv("README.md", joinpath(docdir, "README.md"); force = true)
    write("README.md", readme_file)
    @info "Moved generated readme to docs/"

    # move all md files docs -> docs/src
    docfiles = readdir(docdir)
    mkpath(joinpath(docdir, "src", "images"))
    mv.(joinpath.(docdir, docfiles), joinpath.(docdir, "src", docfiles))
    @info "Moved generated doc files to docs/src"

    cp(joinpath(gendir, "docs.make.jl"), joinpath(docdir, "make.jl"))
    cp(joinpath(gendir, "docs.Project.toml"), joinpath(docdir, "Project.toml"))
    cp(joinpath(gendir, "docs.index.md"), joinpath(docdir, "src", "index.md"))
    cp(joinpath(gendir, "docs.docstrings.md"), joinpath(docdir, "src", "docstrings.md"))
    cp(joinpath(gendir, "device-attribution-image.png"), joinpath(docdir, "src", "images", "device-attribution-image.png"))
    @info "Copied templated documentation files to docs/"

    postprocess_docs(joinpath(docdir, "src"))
    @info "Postprocessed autogenerated documentation."

    postprocess_src(joinpath(devdir, "src"))
    @info "Postprocessed autogenerated source files for replacing some docstrings."

    aproj = Base.active_project()
    Pkg.activate(docdir)
    Pkg.develop("StravaAPI")
    Pkg.activate(aproj)
    @info "Developed StravaAPI in docs project environment for local build."
    return nothing
end

generatepackage()
