# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""MovingStream

    MovingStream(;
        original_size=nothing,
        resolution=nothing,
        series_type=nothing,
        data=nothing,
    )

    - original_size::Int64 : The number of data points in this stream
    - resolution::String : The level of detail (sampling) in which this stream was returned
    - series_type::String : The base series used in the case the stream was downsampled
    - data::Vector{Bool} : The sequence of moving values for this stream, as boolean values
"""
Base.@kwdef mutable struct MovingStream <: OpenAPI.APIModel
    original_size::Union{Nothing, Int64} = nothing
    resolution::Union{Nothing, String} = nothing
    series_type::Union{Nothing, String} = nothing
    data::Union{Nothing, Vector{Bool}} = nothing

    function MovingStream(original_size, resolution, series_type, data, )
        OpenAPI.validate_property(MovingStream, Symbol("original_size"), original_size)
        OpenAPI.validate_property(MovingStream, Symbol("resolution"), resolution)
        OpenAPI.validate_property(MovingStream, Symbol("series_type"), series_type)
        OpenAPI.validate_property(MovingStream, Symbol("data"), data)
        return new(original_size, resolution, series_type, data, )
    end
end # type MovingStream

const _property_types_MovingStream = Dict{Symbol,String}(Symbol("original_size")=>"Int64", Symbol("resolution")=>"String", Symbol("series_type")=>"String", Symbol("data")=>"Vector{Bool}", )
OpenAPI.property_type(::Type{ MovingStream }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovingStream[name]))}

function check_required(o::MovingStream)
    true
end

function OpenAPI.validate_property(::Type{ MovingStream }, name::Symbol, val)


    if name === Symbol("resolution")
        OpenAPI.validate_param(name, "MovingStream", :enum, val, ["low", "medium", "high"])
    end


    if name === Symbol("series_type")
        OpenAPI.validate_param(name, "MovingStream", :enum, val, ["distance", "time"])
    end


end
