# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BaseStream

    BaseStream(;
        original_size=nothing,
        resolution=nothing,
        series_type=nothing,
    )

    - original_size::Int64 : The number of data points in this stream
    - resolution::String : The level of detail (sampling) in which this stream was returned
    - series_type::String : The base series used in the case the stream was downsampled
"""
Base.@kwdef mutable struct BaseStream <: OpenAPI.APIModel
    original_size::Union{Nothing, Int64} = nothing
    resolution::Union{Nothing, String} = nothing
    series_type::Union{Nothing, String} = nothing

    function BaseStream(original_size, resolution, series_type, )
        OpenAPI.validate_property(BaseStream, Symbol("original_size"), original_size)
        OpenAPI.validate_property(BaseStream, Symbol("resolution"), resolution)
        OpenAPI.validate_property(BaseStream, Symbol("series_type"), series_type)
        return new(original_size, resolution, series_type, )
    end
end # type BaseStream

const _property_types_BaseStream = Dict{Symbol,String}(Symbol("original_size")=>"Int64", Symbol("resolution")=>"String", Symbol("series_type")=>"String", )
OpenAPI.property_type(::Type{ BaseStream }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BaseStream[name]))}

function check_required(o::BaseStream)
    true
end

function OpenAPI.validate_property(::Type{ BaseStream }, name::Symbol, val)


    if name === Symbol("resolution")
        OpenAPI.validate_param(name, "BaseStream", :enum, val, ["low", "medium", "high"])
    end


    if name === Symbol("series_type")
        OpenAPI.validate_param(name, "BaseStream", :enum, val, ["distance", "time"])
    end

end
