# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TimedZoneRange
A union type representing the time spent in a given zone.

    TimedZoneRange(;
        min=nothing,
        max=nothing,
        time=nothing,
    )

    - min::Int64 : The minimum value in the range.
    - max::Int64 : The maximum value in the range.
    - time::Int64 : The number of seconds spent in this zone
"""
Base.@kwdef mutable struct TimedZoneRange <: OpenAPI.APIModel
    min::Union{Nothing, Int64} = nothing
    max::Union{Nothing, Int64} = nothing
    time::Union{Nothing, Int64} = nothing

    function TimedZoneRange(min, max, time, )
        OpenAPI.validate_property(TimedZoneRange, Symbol("min"), min)
        OpenAPI.validate_property(TimedZoneRange, Symbol("max"), max)
        OpenAPI.validate_property(TimedZoneRange, Symbol("time"), time)
        return new(min, max, time, )
    end
end # type TimedZoneRange

const _property_types_TimedZoneRange = Dict{Symbol,String}(Symbol("min")=>"Int64", Symbol("max")=>"Int64", Symbol("time")=>"Int64", )
OpenAPI.property_type(::Type{ TimedZoneRange }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TimedZoneRange[name]))}

function check_required(o::TimedZoneRange)
    true
end

function OpenAPI.validate_property(::Type{ TimedZoneRange }, name::Symbol, val)



end
