# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Zones

    Zones(;
        heart_rate=nothing,
        power=nothing,
    )

    - heart_rate::HeartRateZoneRanges
    - power::PowerZoneRanges
"""
Base.@kwdef mutable struct Zones <: OpenAPI.APIModel
    heart_rate = nothing # spec type: Union{ Nothing, HeartRateZoneRanges }
    power = nothing # spec type: Union{ Nothing, PowerZoneRanges }

    function Zones(heart_rate, power, )
        OpenAPI.validate_property(Zones, Symbol("heart_rate"), heart_rate)
        OpenAPI.validate_property(Zones, Symbol("power"), power)
        return new(heart_rate, power, )
    end
end # type Zones

const _property_types_Zones = Dict{Symbol,String}(Symbol("heart_rate")=>"HeartRateZoneRanges", Symbol("power")=>"PowerZoneRanges", )
OpenAPI.property_type(::Type{ Zones }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Zones[name]))}

function check_required(o::Zones)
    true
end

function OpenAPI.validate_property(::Type{ Zones }, name::Symbol, val)
end
