# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""HeartRateZoneRanges

    HeartRateZoneRanges(;
        custom_zones=nothing,
        zones=nothing,
    )

    - custom_zones::Bool : Whether the athlete has set their own custom heart rate zones
    - zones::Vector{ZoneRange}
"""
Base.@kwdef mutable struct HeartRateZoneRanges <: OpenAPI.APIModel
    custom_zones::Union{Nothing, Bool} = nothing
    zones::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ZoneRange} }

    function HeartRateZoneRanges(custom_zones, zones, )
        OpenAPI.validate_property(HeartRateZoneRanges, Symbol("custom_zones"), custom_zones)
        OpenAPI.validate_property(HeartRateZoneRanges, Symbol("zones"), zones)
        return new(custom_zones, zones, )
    end
end # type HeartRateZoneRanges

const _property_types_HeartRateZoneRanges = Dict{Symbol,String}(Symbol("custom_zones")=>"Bool", Symbol("zones")=>"Vector{ZoneRange}", )
OpenAPI.property_type(::Type{ HeartRateZoneRanges }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_HeartRateZoneRanges[name]))}

function check_required(o::HeartRateZoneRanges)
    true
end

function OpenAPI.validate_property(::Type{ HeartRateZoneRanges }, name::Symbol, val)


end
