# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PowerStream

    PowerStream(;
        original_size=nothing,
        resolution=nothing,
        series_type=nothing,
        data=nothing,
    )

    - original_size::Int64 : The number of data points in this stream
    - resolution::String : The level of detail (sampling) in which this stream was returned
    - series_type::String : The base series used in the case the stream was downsampled
    - data::Vector{Int64} : The sequence of power values for this stream, in watts
"""
Base.@kwdef mutable struct PowerStream <: OpenAPI.APIModel
    original_size::Union{Nothing, Int64} = nothing
    resolution::Union{Nothing, String} = nothing
    series_type::Union{Nothing, String} = nothing
    data::Union{Nothing, Vector{Int64}} = nothing

    function PowerStream(original_size, resolution, series_type, data, )
        OpenAPI.validate_property(PowerStream, Symbol("original_size"), original_size)
        OpenAPI.validate_property(PowerStream, Symbol("resolution"), resolution)
        OpenAPI.validate_property(PowerStream, Symbol("series_type"), series_type)
        OpenAPI.validate_property(PowerStream, Symbol("data"), data)
        return new(original_size, resolution, series_type, data, )
    end
end # type PowerStream

const _property_types_PowerStream = Dict{Symbol,String}(Symbol("original_size")=>"Int64", Symbol("resolution")=>"String", Symbol("series_type")=>"String", Symbol("data")=>"Vector{Int64}", )
OpenAPI.property_type(::Type{ PowerStream }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PowerStream[name]))}

function check_required(o::PowerStream)
    true
end

function OpenAPI.validate_property(::Type{ PowerStream }, name::Symbol, val)


    if name === Symbol("resolution")
        OpenAPI.validate_param(name, "PowerStream", :enum, val, ["low", "medium", "high"])
    end


    if name === Symbol("series_type")
        OpenAPI.validate_param(name, "PowerStream", :enum, val, ["distance", "time"])
    end


end
