# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PhotosSummary

    PhotosSummary(;
        count=nothing,
        primary=nothing,
    )

    - count::Int64 : The number of photos
    - primary::PhotosSummaryPrimary
"""
Base.@kwdef mutable struct PhotosSummary <: OpenAPI.APIModel
    count::Union{Nothing, Int64} = nothing
    primary = nothing # spec type: Union{ Nothing, PhotosSummaryPrimary }

    function PhotosSummary(count, primary, )
        OpenAPI.validate_property(PhotosSummary, Symbol("count"), count)
        OpenAPI.validate_property(PhotosSummary, Symbol("primary"), primary)
        return new(count, primary, )
    end
end # type PhotosSummary

const _property_types_PhotosSummary = Dict{Symbol,String}(Symbol("count")=>"Int64", Symbol("primary")=>"PhotosSummaryPrimary", )
OpenAPI.property_type(::Type{ PhotosSummary }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PhotosSummary[name]))}

function check_required(o::PhotosSummary)
    true
end

function OpenAPI.validate_property(::Type{ PhotosSummary }, name::Symbol, val)
end
