# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PolylineMap

    PolylineMap(;
        id=nothing,
        polyline=nothing,
        summary_polyline=nothing,
    )

    - id::String : The identifier of the map
    - polyline::String : The polyline of the map, only returned on detailed representation of an object
    - summary_polyline::String : The summary polyline of the map
"""
Base.@kwdef mutable struct PolylineMap <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    polyline::Union{Nothing, String} = nothing
    summary_polyline::Union{Nothing, String} = nothing

    function PolylineMap(id, polyline, summary_polyline, )
        o = new(id, polyline, summary_polyline, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PolylineMap

const _property_types_PolylineMap = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("polyline")=>"String", Symbol("summary_polyline")=>"String", )
OpenAPI.property_type(::Type{ PolylineMap }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PolylineMap[name]))}

function OpenAPI.check_required(o::PolylineMap)
    true
end

function OpenAPI.validate_properties(o::PolylineMap)
    OpenAPI.validate_property(PolylineMap, Symbol("id"), o.id)
    OpenAPI.validate_property(PolylineMap, Symbol("polyline"), o.polyline)
    OpenAPI.validate_property(PolylineMap, Symbol("summary_polyline"), o.summary_polyline)
end

function OpenAPI.validate_property(::Type{ PolylineMap }, name::Symbol, val)



end

