# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PowerZoneRanges

    PowerZoneRanges(;
        zones=nothing,
    )

    - zones::Vector{ZoneRange}
"""
Base.@kwdef mutable struct PowerZoneRanges <: OpenAPI.APIModel
    zones::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ZoneRange} }

    function PowerZoneRanges(zones, )
        OpenAPI.validate_property(PowerZoneRanges, Symbol("zones"), zones)
        return new(zones, )
    end
end # type PowerZoneRanges

const _property_types_PowerZoneRanges = Dict{Symbol,String}(Symbol("zones")=>"Vector{ZoneRange}", )
OpenAPI.property_type(::Type{ PowerZoneRanges }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PowerZoneRanges[name]))}

function check_required(o::PowerZoneRanges)
    true
end

function OpenAPI.validate_property(::Type{ PowerZoneRanges }, name::Symbol, val)

end
