# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ZoneRange

    ZoneRange(;
        min=nothing,
        max=nothing,
    )

    - min::Int64 : The minimum value in the range.
    - max::Int64 : The maximum value in the range.
"""
Base.@kwdef mutable struct ZoneRange <: OpenAPI.APIModel
    min::Union{Nothing, Int64} = nothing
    max::Union{Nothing, Int64} = nothing

    function ZoneRange(min, max, )
        o = new(min, max, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ZoneRange

const _property_types_ZoneRange = Dict{Symbol,String}(Symbol("min")=>"Int64", Symbol("max")=>"Int64", )
OpenAPI.property_type(::Type{ ZoneRange }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ZoneRange[name]))}

function OpenAPI.check_required(o::ZoneRange)
    true
end

function OpenAPI.validate_properties(o::ZoneRange)
    OpenAPI.validate_property(ZoneRange, Symbol("min"), o.min)
    OpenAPI.validate_property(ZoneRange, Symbol("max"), o.max)
end

function OpenAPI.validate_property(::Type{ ZoneRange }, name::Symbol, val)


end

