# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DetailedAthlete

    DetailedAthlete(;
        id=nothing,
        resource_state=nothing,
        firstname=nothing,
        lastname=nothing,
        profile_medium=nothing,
        profile=nothing,
        city=nothing,
        state=nothing,
        country=nothing,
        sex=nothing,
        premium=nothing,
        summit=nothing,
        created_at=nothing,
        updated_at=nothing,
        follower_count=nothing,
        friend_count=nothing,
        measurement_preference=nothing,
        ftp=nothing,
        weight=nothing,
        clubs=nothing,
        bikes=nothing,
        shoes=nothing,
    )

    - id::Int64 : The unique identifier of the athlete
    - resource_state::Int64 : Resource state, indicates level of detail. Possible values: 1 -&gt; \&quot;meta\&quot;, 2 -&gt; \&quot;summary\&quot;, 3 -&gt; \&quot;detail\&quot;
    - firstname::String : The athlete&#39;s first name.
    - lastname::String : The athlete&#39;s last name.
    - profile_medium::String : URL to a 62x62 pixel profile picture.
    - profile::String : URL to a 124x124 pixel profile picture.
    - city::String : The athlete&#39;s city.
    - state::String : The athlete&#39;s state or geographical region.
    - country::String : The athlete&#39;s country.
    - sex::String : The athlete&#39;s sex.
    - premium::Bool : Deprecated.  Use summit field instead. Whether the athlete has any Summit subscription.
    - summit::Bool : Whether the athlete has any Summit subscription.
    - created_at::ZonedDateTime : The time at which the athlete was created.
    - updated_at::ZonedDateTime : The time at which the athlete was last updated.
    - follower_count::Int64 : The athlete&#39;s follower count.
    - friend_count::Int64 : The athlete&#39;s friend count.
    - measurement_preference::String : The athlete&#39;s preferred unit system.
    - ftp::Int64 : The athlete&#39;s FTP (Functional Threshold Power).
    - weight::Float32 : The athlete&#39;s weight.
    - clubs::Vector{SummaryClub} : The athlete&#39;s clubs.
    - bikes::Vector{SummaryGear} : The athlete&#39;s bikes.
    - shoes::Vector{SummaryGear} : The athlete&#39;s shoes.
"""
Base.@kwdef mutable struct DetailedAthlete <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    resource_state::Union{Nothing, Int64} = nothing
    firstname::Union{Nothing, String} = nothing
    lastname::Union{Nothing, String} = nothing
    profile_medium::Union{Nothing, String} = nothing
    profile::Union{Nothing, String} = nothing
    city::Union{Nothing, String} = nothing
    state::Union{Nothing, String} = nothing
    country::Union{Nothing, String} = nothing
    sex::Union{Nothing, String} = nothing
    premium::Union{Nothing, Bool} = nothing
    summit::Union{Nothing, Bool} = nothing
    created_at::Union{Nothing, ZonedDateTime} = nothing
    updated_at::Union{Nothing, ZonedDateTime} = nothing
    follower_count::Union{Nothing, Int64} = nothing
    friend_count::Union{Nothing, Int64} = nothing
    measurement_preference::Union{Nothing, String} = nothing
    ftp::Union{Nothing, Int64} = nothing
    weight::Union{Nothing, Float32} = nothing
    clubs::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{SummaryClub} }
    bikes::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{SummaryGear} }
    shoes::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{SummaryGear} }

    function DetailedAthlete(id, resource_state, firstname, lastname, profile_medium, profile, city, state, country, sex, premium, summit, created_at, updated_at, follower_count, friend_count, measurement_preference, ftp, weight, clubs, bikes, shoes, )
        OpenAPI.validate_property(DetailedAthlete, Symbol("id"), id)
        OpenAPI.validate_property(DetailedAthlete, Symbol("resource_state"), resource_state)
        OpenAPI.validate_property(DetailedAthlete, Symbol("firstname"), firstname)
        OpenAPI.validate_property(DetailedAthlete, Symbol("lastname"), lastname)
        OpenAPI.validate_property(DetailedAthlete, Symbol("profile_medium"), profile_medium)
        OpenAPI.validate_property(DetailedAthlete, Symbol("profile"), profile)
        OpenAPI.validate_property(DetailedAthlete, Symbol("city"), city)
        OpenAPI.validate_property(DetailedAthlete, Symbol("state"), state)
        OpenAPI.validate_property(DetailedAthlete, Symbol("country"), country)
        OpenAPI.validate_property(DetailedAthlete, Symbol("sex"), sex)
        OpenAPI.validate_property(DetailedAthlete, Symbol("premium"), premium)
        OpenAPI.validate_property(DetailedAthlete, Symbol("summit"), summit)
        OpenAPI.validate_property(DetailedAthlete, Symbol("created_at"), created_at)
        OpenAPI.validate_property(DetailedAthlete, Symbol("updated_at"), updated_at)
        OpenAPI.validate_property(DetailedAthlete, Symbol("follower_count"), follower_count)
        OpenAPI.validate_property(DetailedAthlete, Symbol("friend_count"), friend_count)
        OpenAPI.validate_property(DetailedAthlete, Symbol("measurement_preference"), measurement_preference)
        OpenAPI.validate_property(DetailedAthlete, Symbol("ftp"), ftp)
        OpenAPI.validate_property(DetailedAthlete, Symbol("weight"), weight)
        OpenAPI.validate_property(DetailedAthlete, Symbol("clubs"), clubs)
        OpenAPI.validate_property(DetailedAthlete, Symbol("bikes"), bikes)
        OpenAPI.validate_property(DetailedAthlete, Symbol("shoes"), shoes)
        return new(id, resource_state, firstname, lastname, profile_medium, profile, city, state, country, sex, premium, summit, created_at, updated_at, follower_count, friend_count, measurement_preference, ftp, weight, clubs, bikes, shoes, )
    end
end # type DetailedAthlete

const _property_types_DetailedAthlete = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("resource_state")=>"Int64", Symbol("firstname")=>"String", Symbol("lastname")=>"String", Symbol("profile_medium")=>"String", Symbol("profile")=>"String", Symbol("city")=>"String", Symbol("state")=>"String", Symbol("country")=>"String", Symbol("sex")=>"String", Symbol("premium")=>"Bool", Symbol("summit")=>"Bool", Symbol("created_at")=>"ZonedDateTime", Symbol("updated_at")=>"ZonedDateTime", Symbol("follower_count")=>"Int64", Symbol("friend_count")=>"Int64", Symbol("measurement_preference")=>"String", Symbol("ftp")=>"Int64", Symbol("weight")=>"Float32", Symbol("clubs")=>"Vector{SummaryClub}", Symbol("bikes")=>"Vector{SummaryGear}", Symbol("shoes")=>"Vector{SummaryGear}", )
OpenAPI.property_type(::Type{ DetailedAthlete }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DetailedAthlete[name]))}

function check_required(o::DetailedAthlete)
    true
end

function OpenAPI.validate_property(::Type{ DetailedAthlete }, name::Symbol, val)

    if name === Symbol("id")
        OpenAPI.validate_param(name, "DetailedAthlete", :format, val, "int64")
    end









    if name === Symbol("sex")
        OpenAPI.validate_param(name, "DetailedAthlete", :enum, val, ["M", "F"])
    end




    if name === Symbol("created_at")
        OpenAPI.validate_param(name, "DetailedAthlete", :format, val, "date-time")
    end

    if name === Symbol("updated_at")
        OpenAPI.validate_param(name, "DetailedAthlete", :format, val, "date-time")
    end



    if name === Symbol("measurement_preference")
        OpenAPI.validate_param(name, "DetailedAthlete", :enum, val, ["feet", "meters"])
    end



    if name === Symbol("weight")
        OpenAPI.validate_param(name, "DetailedAthlete", :format, val, "float")
    end



end
