# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SmoothGradeStream

    SmoothGradeStream(;
        original_size=nothing,
        resolution=nothing,
        series_type=nothing,
        data=nothing,
    )

    - original_size::Int64 : The number of data points in this stream
    - resolution::String : The level of detail (sampling) in which this stream was returned
    - series_type::String : The base series used in the case the stream was downsampled
    - data::Vector{Float32} : The sequence of grade values for this stream, as percents of a grade
"""
Base.@kwdef mutable struct SmoothGradeStream <: OpenAPI.APIModel
    original_size::Union{Nothing, Int64} = nothing
    resolution::Union{Nothing, String} = nothing
    series_type::Union{Nothing, String} = nothing
    data::Union{Nothing, Vector{Float32}} = nothing

    function SmoothGradeStream(original_size, resolution, series_type, data, )
        OpenAPI.validate_property(SmoothGradeStream, Symbol("original_size"), original_size)
        OpenAPI.validate_property(SmoothGradeStream, Symbol("resolution"), resolution)
        OpenAPI.validate_property(SmoothGradeStream, Symbol("series_type"), series_type)
        OpenAPI.validate_property(SmoothGradeStream, Symbol("data"), data)
        return new(original_size, resolution, series_type, data, )
    end
end # type SmoothGradeStream

const _property_types_SmoothGradeStream = Dict{Symbol,String}(Symbol("original_size")=>"Int64", Symbol("resolution")=>"String", Symbol("series_type")=>"String", Symbol("data")=>"Vector{Float32}", )
OpenAPI.property_type(::Type{ SmoothGradeStream }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SmoothGradeStream[name]))}

function check_required(o::SmoothGradeStream)
    true
end

function OpenAPI.validate_property(::Type{ SmoothGradeStream }, name::Symbol, val)


    if name === Symbol("resolution")
        OpenAPI.validate_param(name, "SmoothGradeStream", :enum, val, ["low", "medium", "high"])
    end


    if name === Symbol("series_type")
        OpenAPI.validate_param(name, "SmoothGradeStream", :enum, val, ["distance", "time"])
    end


end
