# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TimeStream

    TimeStream(;
        original_size=nothing,
        resolution=nothing,
        series_type=nothing,
        data=nothing,
    )

    - original_size::Int64 : The number of data points in this stream
    - resolution::String : The level of detail (sampling) in which this stream was returned
    - series_type::String : The base series used in the case the stream was downsampled
    - data::Vector{Int64} : The sequence of time values for this stream, in seconds
"""
Base.@kwdef mutable struct TimeStream <: OpenAPI.APIModel
    original_size::Union{Nothing, Int64} = nothing
    resolution::Union{Nothing, String} = nothing
    series_type::Union{Nothing, String} = nothing
    data::Union{Nothing, Vector{Int64}} = nothing

    function TimeStream(original_size, resolution, series_type, data, )
        OpenAPI.validate_property(TimeStream, Symbol("original_size"), original_size)
        OpenAPI.validate_property(TimeStream, Symbol("resolution"), resolution)
        OpenAPI.validate_property(TimeStream, Symbol("series_type"), series_type)
        OpenAPI.validate_property(TimeStream, Symbol("data"), data)
        return new(original_size, resolution, series_type, data, )
    end
end # type TimeStream

const _property_types_TimeStream = Dict{Symbol,String}(Symbol("original_size")=>"Int64", Symbol("resolution")=>"String", Symbol("series_type")=>"String", Symbol("data")=>"Vector{Int64}", )
OpenAPI.property_type(::Type{ TimeStream }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TimeStream[name]))}

function check_required(o::TimeStream)
    true
end

function OpenAPI.validate_property(::Type{ TimeStream }, name::Symbol, val)


    if name === Symbol("resolution")
        OpenAPI.validate_param(name, "TimeStream", :enum, val, ["low", "medium", "high"])
    end


    if name === Symbol("series_type")
        OpenAPI.validate_param(name, "TimeStream", :enum, val, ["distance", "time"])
    end


end
