# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Error

    Error(;
        code=nothing,
        field=nothing,
        resource=nothing,
    )

    - code::String : The code associated with this error.
    - field::String : The specific field or aspect of the resource associated with this error.
    - resource::String : The type of resource associated with this error.
"""
Base.@kwdef mutable struct Error <: OpenAPI.APIModel
    code::Union{Nothing, String} = nothing
    field::Union{Nothing, String} = nothing
    resource::Union{Nothing, String} = nothing

    function Error(code, field, resource, )
        OpenAPI.validate_property(Error, Symbol("code"), code)
        OpenAPI.validate_property(Error, Symbol("field"), field)
        OpenAPI.validate_property(Error, Symbol("resource"), resource)
        return new(code, field, resource, )
    end
end # type Error

const _property_types_Error = Dict{Symbol,String}(Symbol("code")=>"String", Symbol("field")=>"String", Symbol("resource")=>"String", )
OpenAPI.property_type(::Type{ Error }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Error[name]))}

function check_required(o::Error)
    true
end

function OpenAPI.validate_property(::Type{ Error }, name::Symbol, val)
end
