# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""LatLngStream

    LatLngStream(;
        original_size=nothing,
        resolution=nothing,
        series_type=nothing,
        data=nothing,
    )

    - original_size::Int64 : The number of data points in this stream
    - resolution::String : The level of detail (sampling) in which this stream was returned
    - series_type::String : The base series used in the case the stream was downsampled
    - data::Vector{Vector} : The sequence of lat/long values for this stream
"""
Base.@kwdef mutable struct LatLngStream <: OpenAPI.APIModel
    original_size::Union{Nothing, Int64} = nothing
    resolution::Union{Nothing, String} = nothing
    series_type::Union{Nothing, String} = nothing
    data::Union{Nothing, Vector{Vector}} = nothing

    function LatLngStream(original_size, resolution, series_type, data, )
        OpenAPI.validate_property(LatLngStream, Symbol("original_size"), original_size)
        OpenAPI.validate_property(LatLngStream, Symbol("resolution"), resolution)
        OpenAPI.validate_property(LatLngStream, Symbol("series_type"), series_type)
        OpenAPI.validate_property(LatLngStream, Symbol("data"), data)
        return new(original_size, resolution, series_type, data, )
    end
end # type LatLngStream

const _property_types_LatLngStream = Dict{Symbol,String}(Symbol("original_size")=>"Int64", Symbol("resolution")=>"String", Symbol("series_type")=>"String", Symbol("data")=>"Vector{Vector}", )
OpenAPI.property_type(::Type{ LatLngStream }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_LatLngStream[name]))}

function check_required(o::LatLngStream)
    true
end

function OpenAPI.validate_property(::Type{ LatLngStream }, name::Symbol, val)
    if name === Symbol("resolution")
        OpenAPI.validate_param(name, "LatLngStream", :enum, val, ["low", "medium", "high"])
    end
    if name === Symbol("series_type")
        OpenAPI.validate_param(name, "LatLngStream", :enum, val, ["distance", "time"])
    end
end
