# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ExplorerResponse

    ExplorerResponse(;
        segments=nothing,
    )

    - segments::Vector{ExplorerSegment} : The set of segments matching an explorer request
"""
Base.@kwdef mutable struct ExplorerResponse <: OpenAPI.APIModel
    segments::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ExplorerSegment} }

    function ExplorerResponse(segments, )
        OpenAPI.validate_property(ExplorerResponse, Symbol("segments"), segments)
        return new(segments, )
    end
end # type ExplorerResponse

const _property_types_ExplorerResponse = Dict{Symbol,String}(Symbol("segments")=>"Vector{ExplorerSegment}", )
OpenAPI.property_type(::Type{ ExplorerResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ExplorerResponse[name]))}

function check_required(o::ExplorerResponse)
    true
end

function OpenAPI.validate_property(::Type{ ExplorerResponse }, name::Symbol, val)
end
