# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SummaryGear

    SummaryGear(;
        id=nothing,
        resource_state=nothing,
        primary=nothing,
        name=nothing,
        distance=nothing,
    )

    - id::String : The gear&#39;s unique identifier.
    - resource_state::Int64 : Resource state, indicates level of detail. Possible values: 2 -&gt; \&quot;summary\&quot;, 3 -&gt; \&quot;detail\&quot;
    - primary::Bool : Whether this gear&#39;s is the owner&#39;s default one.
    - name::String : The gear&#39;s name.
    - distance::Float32 : The distance logged with this gear.
"""
Base.@kwdef mutable struct SummaryGear <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    resource_state::Union{Nothing, Int64} = nothing
    primary::Union{Nothing, Bool} = nothing
    name::Union{Nothing, String} = nothing
    distance::Union{Nothing, Float32} = nothing

    function SummaryGear(id, resource_state, primary, name, distance, )
        o = new(id, resource_state, primary, name, distance, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type SummaryGear

const _property_types_SummaryGear = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("resource_state")=>"Int64", Symbol("primary")=>"Bool", Symbol("name")=>"String", Symbol("distance")=>"Float32", )
OpenAPI.property_type(::Type{ SummaryGear }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SummaryGear[name]))}

function OpenAPI.check_required(o::SummaryGear)
    true
end

function OpenAPI.validate_properties(o::SummaryGear)
    OpenAPI.validate_property(SummaryGear, Symbol("id"), o.id)
    OpenAPI.validate_property(SummaryGear, Symbol("resource_state"), o.resource_state)
    OpenAPI.validate_property(SummaryGear, Symbol("primary"), o.primary)
    OpenAPI.validate_property(SummaryGear, Symbol("name"), o.name)
    OpenAPI.validate_property(SummaryGear, Symbol("distance"), o.distance)
end

function OpenAPI.validate_property(::Type{ SummaryGear }, name::Symbol, val)





    if name === Symbol("distance")
        OpenAPI.validate_param(name, "SummaryGear", :format, val, "float")
    end
end

