# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DistanceStream

    DistanceStream(;
        original_size=nothing,
        resolution=nothing,
        series_type=nothing,
        data=nothing,
    )

    - original_size::Int64 : The number of data points in this stream
    - resolution::String : The level of detail (sampling) in which this stream was returned
    - series_type::String : The base series used in the case the stream was downsampled
    - data::Vector{Float32} : The sequence of distance values for this stream, in meters
"""
Base.@kwdef mutable struct DistanceStream <: OpenAPI.APIModel
    original_size::Union{Nothing, Int64} = nothing
    resolution::Union{Nothing, String} = nothing
    series_type::Union{Nothing, String} = nothing
    data::Union{Nothing, Vector{Float32}} = nothing

    function DistanceStream(original_size, resolution, series_type, data, )
        OpenAPI.validate_property(DistanceStream, Symbol("original_size"), original_size)
        OpenAPI.validate_property(DistanceStream, Symbol("resolution"), resolution)
        OpenAPI.validate_property(DistanceStream, Symbol("series_type"), series_type)
        OpenAPI.validate_property(DistanceStream, Symbol("data"), data)
        return new(original_size, resolution, series_type, data, )
    end
end # type DistanceStream

const _property_types_DistanceStream = Dict{Symbol,String}(Symbol("original_size")=>"Int64", Symbol("resolution")=>"String", Symbol("series_type")=>"String", Symbol("data")=>"Vector{Float32}", )
OpenAPI.property_type(::Type{ DistanceStream }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DistanceStream[name]))}

function check_required(o::DistanceStream)
    true
end

function OpenAPI.validate_property(::Type{ DistanceStream }, name::Symbol, val)


    if name === Symbol("resolution")
        OpenAPI.validate_param(name, "DistanceStream", :enum, val, ["low", "medium", "high"])
    end


    if name === Symbol("series_type")
        OpenAPI.validate_param(name, "DistanceStream", :enum, val, ["distance", "time"])
    end


end
