# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Comment

    Comment(;
        id=nothing,
        activity_id=nothing,
        text=nothing,
        athlete=nothing,
        created_at=nothing,
    )

    - id::Int64 : The unique identifier of this comment
    - activity_id::Int64 : The identifier of the activity this comment is related to
    - text::String : The content of the comment
    - athlete::SummaryAthlete
    - created_at::ZonedDateTime : The time at which this comment was created.
"""
Base.@kwdef mutable struct Comment <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    activity_id::Union{Nothing, Int64} = nothing
    text::Union{Nothing, String} = nothing
    athlete = nothing # spec type: Union{ Nothing, SummaryAthlete }
    created_at::Union{Nothing, ZonedDateTime} = nothing

    function Comment(id, activity_id, text, athlete, created_at, )
        OpenAPI.validate_property(Comment, Symbol("id"), id)
        OpenAPI.validate_property(Comment, Symbol("activity_id"), activity_id)
        OpenAPI.validate_property(Comment, Symbol("text"), text)
        OpenAPI.validate_property(Comment, Symbol("athlete"), athlete)
        OpenAPI.validate_property(Comment, Symbol("created_at"), created_at)
        return new(id, activity_id, text, athlete, created_at, )
    end
end # type Comment

const _property_types_Comment = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("activity_id")=>"Int64", Symbol("text")=>"String", Symbol("athlete")=>"SummaryAthlete", Symbol("created_at")=>"ZonedDateTime", )
OpenAPI.property_type(::Type{ Comment }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Comment[name]))}

function check_required(o::Comment)
    true
end

function OpenAPI.validate_property(::Type{ Comment }, name::Symbol, val)

    if name === Symbol("id")
        OpenAPI.validate_param(name, "Comment", :format, val, "int64")
    end

    if name === Symbol("activity_id")
        OpenAPI.validate_param(name, "Comment", :format, val, "int64")
    end



    if name === Symbol("created_at")
        OpenAPI.validate_param(name, "Comment", :format, val, "date-time")
    end
end
