# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

module StravaAPI

using Dates, TimeZones
using OpenAPI
using OpenAPI.Clients

const API_VERSION = "3.0.0"

include("modelincludes.jl")
include("authentication.jl")

include("apis/api_ActivitiesApi.jl")
include("apis/api_AthletesApi.jl")
include("apis/api_ClubsApi.jl")
include("apis/api_GearsApi.jl")
include("apis/api_RoutesApi.jl")
include("apis/api_SegmentEffortsApi.jl")
include("apis/api_SegmentsApi.jl")
include("apis/api_StreamsApi.jl")
include("apis/api_UploadsApi.jl")

end # module StravaAPI
